evaluation:
    path: /
    defaults: { _controller: App\Controller\Back\EvaluationController:index }

evaluation.create:
    path: /create
    defaults: { _controller: App\Controller\Back\EvaluationController:create }

evaluation.update:
    path: /{id}/update
    defaults: { _controller: App\Controller\Back\EvaluationController:update }
    requirements:
        id: \d+

evaluation.delete:
    path: /{id}/delete
    defaults: { _controller: App\Controller\Back\EvaluationController:delete }
    requirements:
        id: \d+

evaluation.print:
    path: /{id}/print
    defaults: { _controller: App\Controller\Back\EvaluationController:print }
    requirements:
        id: \d+

evaluation.run:
    path: /{id}/run
    defaults: { _controller: App\Controller\Back\EvaluationController:run }
    requirements:
        id: \d+
