admin.index:
    path: /
    controller: App\Controller\Back\DefaultController::index

admin.category:
    resource: category.yaml
    prefix: /category

admin.question:
    resource: question.yaml
    prefix: /question

admin.evaluation:
    resource: evaluation.yaml
    prefix: /evaluation
